name: pantau_pro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.1.2
  http: ^1.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - Asset/image/
    - Asset/image/background.jpg

  fonts:
    - family: MonomaniacOne
      fonts:
        - asset: Asset/font/MonomaniacOne-Regular.ttf
    - family: Man
      fonts:
        - asset: Asset/font/Roundman.ttf
